version: '3'

networks:
  crusher-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.23.0/24

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - crusher-network

  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=crusher
    networks:
      - crusher-network

  crusher:
    networks:
      - crusher-network
    build:
      context: ../../
      dockerfile: docker/ee/Dockerfile.complete
    depends_on:
      - postgres
      - redis
    environment:
      - LOGDNA_API_KEY=c7bdd500e3cfbfe457a2ec4168b8cfaa
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=crusher
      - DB_PORT=5432
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/crusher
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - STANDALONE_APP_URL=$STANDALONE_APP_URL
      - NEXT_PUBLIC_CRUSHER_MODE=enterprise
      - NEXT_PUBLIC_INTERNAL_BACKEND_URL=$STANDALONE_APP_URL/server
    ports:
      - '3000:3000'
      - '3001:3001'
    links:
      - 'postgres:mysql'
      - 'redis:redis'
    container_name: 'crusher'
    stdin_open: true # docker run -i
    tty: true