name: Deploy Crusher Server

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.19.1

      - name: Install yarn
        run: npm install -g yarn

      - name: Install crusher modules
        run: yarn

      - name: Install webpack
        run: npm install -g webpack

      - name: Package crusher-server for deployment
        run: sh scripts/build-crusher-server.sh

      - name: Download task definition
        run: |
          docker build . --file ci/crusher-server/Dockerfile --tag gcr.io/prepstart/crusher-server:latest
