name: Test electron app

on:
  push:
    branches:
      - fx-tests

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2
          cache: 'pnpm'

      - name: Create ecosystem.config.js and Copy .env.sample file
        run: cp ecosystem.config.sample.js ecosystem.config.js && cp .env.sample .env

      - name: Install crusher modules
        run: pnpm install --frozen-lockfile

      - name: Setup crusher for prod
        run: pnpm setup:prod

      - name: Build electron app
        run: cd packages/electron-app && BACKEND_URL=https://backend.crusher.dev FRONTEND_URL=https://app.crusher.dev pnpm build

      - name: 'Run tests for electron app'
        run: |
          cd packages/electron-app && pnpm tests
